name: Cleaning

on:
  schedule:
    - cron: '1 8 * * 1'
  # watch:
  #   types: started

jobs:

  Cleanup-Old-Releases:
    runs-on: ubuntu-22.04
    if: github.repository_owner_id == github.event.sender.id || github.event_name == 'schedule'
    steps:
    - name: Delete Older Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 4
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Cleanup-Old-Artifacts:
    runs-on: ubuntu-22.04
    if: github.repository_owner_id == github.event.sender.id || github.event_name == 'schedule'
    steps:
    - name: Cleanup Old Action Artifacts
      uses: heidi-pay/gha-delete-artifacts@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        days: 30
        max-artifacts-to-delete: 100
        dry-run: no

  Cleanup-Workflow-Logs:
    runs-on: ubuntu-22.04
    if: github.repository_owner_id == github.event.sender.id || github.event_name == 'schedule'
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 6
