name: R2S Openwrt 21.02

on:
  # push:
  #   branches:
  #     - 21.02
  #   paths:
  #     - '.github/workflows/R2S-Openwrt-21.02.yml'
  schedule:
    - cron: '00 04 * * 1'
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@main
      - name: Show system
        run: |
          echo -e "Total CPU cores\t: $(nproc)"
          cat /proc/cpuinfo | grep 'model name'
          free -h
          uname -a
          [ -f /proc/version ] && cat /proc/version
          [ -f /etc/issue.net ] && cat /etc/issue.net
          [ -f /etc/issue ] && cat /etc/issue
          ulimit -a
      - name: Free disk space
        run: |
          sudo -E swapoff -a
          sudo -E rm -f /swapfile
          sudo -E docker image prune -a -f
          sudo -E snap set system refresh.retain=2
          sudo -E apt-get -y purge azure* dotnet* firefox ghc* google* hhvm llvm* mono* mysql* openjdk* php* zulu*
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo -E rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /etc/mysql /etc/php /usr/local/share/boost
          [ -n "$AGENT_TOOLSDIRECTORY" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Init build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E rm -rf /etc/apt/sources.list.d
          sudo -E apt-get update -y
          sudo -E apt-get install -y build-essential rsync asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python3 python3-pip python3-ply haveged lrzsz device-tree-compiler scons
          wget -qO - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | sed 's/python-/python3-/g' | /bin/bash
          sudo -E apt-get clean -y
          git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
          df -h
      - name: Prepare Sources
        run: |
          sudo chown -R runner:runner /home/runner/work/R2S-R4S-OpenWrt
          cp -r ./SCRIPTS/get_ready.sh ./get_ready.sh
          /bin/bash get_ready.sh
      - name: Prepare Package
        run: |
          cd openwrt
          cp -r ../SCRIPTS/prepare_package.sh ./prepare_package.sh
          /bin/bash prepare_package.sh
          cp -r ../SCRIPTS/target_r2s.sh ./target_r2s.sh
          /bin/bash target_r2s.sh
      - name: Make Config
        run: |
          cd openwrt
          mv ../SEED/config_r2s.seed .config
          #echo -e 'CONFIG_DEVEL=y\nCONFIG_CCACHE=y' >> .config
          make defconfig
      - name: Get Architecture
        working-directory: ${{ github.workspace }}/openwrt
        run: |
          TARGET_DEVICE_ARCH="$(grep "^CONFIG_TARGET_.*_.*=y$" ".config" | head -n 1 | sed 's/^CONFIG_TARGET_//g' | awk -F '_' '{print $1}')"
          echo "TARGET_DEVICE_ARCH=${TARGET_DEVICE_ARCH}-" >>$GITHUB_ENV
          latest_release="$(curl -s https://github.com/openwrt/openwrt/tags | grep -Eo "v[0-9\.]+\-*r*c*[0-9]*.tar.gz" | sed -n '/[2-9][0-9]/p' | sed -n 1p | sed 's/.tar.gz//g' | sed 's/v//g')"
          echo "latest_release=${latest_release}" >>$GITHUB_ENV
      - name: Cache
        uses: klever1988/cachewrtbuild@test
        with:
          ccache: 'true'
          mixkey: ${{ env.TARGET_DEVICE_ARCH }}
          prefix: ${{ github.workspace }}/openwrt
      - name: Make Download
        run: |
          df -h
          cd openwrt
          make download -j50
      - name: Compile Openwrt
        id: compileopenwrt
        continue-on-error: true
        run: |
          df -h
          cd openwrt
          make -j$(($(nproc) + 1)) || make -j$(($(nproc) + 1)) V=s
          echo $?
      - name: If Error
        if: steps.compileopenwrt.outcome == 'failure'
        run: |
          cat openwrt/.config
          echo '================================================================'
          cd openwrt && make -j1 V=s
      - name: Print Disk Space After
        run: df -h
      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          mv openwrt/bin/targets/rockchip/armv8/*sysupgrade.img* ./artifact/
          cd ./artifact/
          gzip -d *.gz && exit 0
          gzip *.img
          sha256sum *.gz | tee R2S-OPoA-${{ env.latest_release }}-$(date +%Y-%m-%d).sha256sum
          mv *ext4* ./R2S-OPoA-${{ env.latest_release }}-$(date +%Y-%m-%d)-ext4.img.gz
          mv *squashfs* ./R2S-OPoA-${{ env.latest_release }}-$(date +%Y-%m-%d)-sfs.img.gz
          cd ../openwrt
          cp .config ../artifact/R2S-config-full.seed
          ./scripts/diffconfig.sh > ../artifact/R2S-config-diff.seed
          artifact_tag="R2S-OPoA-${{ env.latest_release }}-$(date +%Y-%m-%d)"
          release_tag="R2S-R4S-OPoA-${{ env.latest_release }}-$(date +%Y-%m-%d)"
          echo "##[set-output name=artifact_tag;]$artifact_tag"
          echo "##[set-output name=release_tag;]$release_tag"
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ steps.assemble_artifact.outputs.artifact_tag }}-artifact
          path: ./artifact/
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1.9.0
        with:
          name: ${{ steps.assemble_artifact.outputs.release_tag }}-ROM
          allowUpdates: true
          tag: ${{ steps.assemble_artifact.outputs.release_tag }}
          commit: 21.02
          replacesArtifacts: true
          draft: false
          prerelease: false
          token: ${{ secrets.workflow_token }}
          artifacts: ./artifact/*.gz,./artifact/*.seed,./artifact/*.sha256sum
